id: baseline
pretrained: /content/EfficientDet-Pytorch-Detection/runs/baseline-2021_03_09-14_25_30/best_loss.pth
seed: 42
threshold: 0.5 
obj_list: ['pieces', 'bishop', 'black-bishop', 'black-king', 'black-knight', 'black-pawn', 'black-queen', 'black-rook', 'white-bishop', 'white-king', 'white-knight', 'white-pawn', 'white-queen', 'white-rook']
model:
    name: EfficientDet
    args:
        num_classes: 14
        compound_coef: 0

dataset:
    train:
        name: CocoDataset
        args:
            path_to_json: /content/Chess/annotations/instances_train.json
            img_dir: /content/Chess/Images/train
            set: train
            transform: True
            # ... more args
        loader:
            name: DataLoader
            args:
                shuffle: True
                batch_size: 16
                num_workers: 8
                collate_fn: collater
                
    val:
        name: CocoDataset
        args:
            path_to_json: /content/Chess/annotations/instances_valid.json
            img_dir: /content/Chess/Images/valid
            set: val 
            transform: True 
            # ... more args
        loader:
            name: DataLoader
            args:
                shuffle: False
                batch_size: 16
                num_workers: 8
                collate_fn: collater
