id: baseline
pretrained: None
seed: 42
obj_list: ['pieces', 'bishop', 'black-bishop', 'black-king', 'black-knight', 'black-pawn', 'black-queen', 'black-rook', 'white-bishop', 'white-king', 'white-knight', 'white-pawn', 'white-queen', 'white-rook']
model:
    name: EfficientDet
    args:
        num_classes: 14
        compound_coef: 0
        
optimizer:
    name: Adam
    args:
        lr: 0.001
        # momentum: 0.9
        # nesterov: True 
        # <argument keyword>: <argument value>
        # ... more args
loss:
    name: FocalLoss
    args:
        #<argument keyword>: <argument value>
        # ... more args
metric:
    - name: Accuracy
      args:
          #<argument keyword>: <argument value>
          # ... more args
    # ... more metrics
scheduler:
    name: ReduceLROnPlateau
    args:
        mode: min
        factor: 0.5
        patience: 3
        verbose: True

dataset:
    train:
        name: CocoDataset
        args:
            path_to_json: /content/Chess/annotations/instances_train.json
            img_dir: /content/Chess/Images/train
            set: train
            transform: True
            # ... more args
        loader:
            name: DataLoader
            args:
                shuffle: True
                batch_size: 16
                num_workers: 8
                collate_fn: collater
                
    val:
        name: CocoDataset
        args:
            path_to_json: /content/Chess/annotations/instances_valid.json
            img_dir: /content/Chess/Images/valid
            set: val 
            transform: True 
            # ... more args
        loader:
            name: DataLoader
            args:
                shuffle: False
                batch_size: 16
                num_workers: 8
                collate_fn: collater
trainer:
    nepochs: 100
    val_step: 1
    log_step: 1
    save_dir: runs
